# Generated by Django 6.0.2 on 2026-02-04 06:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Original CSV filename', max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when dataset was uploaded')),
                ('total_records', models.IntegerField(help_text='Total number of equipment records in this dataset', validators=[django.core.validators.MinValueValidator(1, message='Dataset must have at least 1 record'), django.core.validators.MaxValueValidator(10000, message='Dataset exceeds maximum allowed rows')])),
                ('avg_flowrate', models.FloatField(help_text='Average flowrate (m³/h)', validators=[django.core.validators.MinValueValidator(0.0, message='Flowrate cannot be negative'), django.core.validators.MaxValueValidator(10000.0, message='Flowrate value is unrealistic')])),
                ('avg_pressure', models.FloatField(help_text='Average pressure (bar)', validators=[django.core.validators.MinValueValidator(0.0, message='Pressure cannot be negative'), django.core.validators.MaxValueValidator(1000.0, message='Pressure value is unrealistic')])),
                ('avg_temperature', models.FloatField(help_text='Average temperature (°C)', validators=[django.core.validators.MinValueValidator(-273.15, message='Temperature below absolute zero'), django.core.validators.MaxValueValidator(5000.0, message='Temperature value is unrealistic')])),
                ('type_distribution', models.JSONField(default=dict, help_text='Dictionary storing count of each equipment type')),
            ],
            options={
                'verbose_name': 'Dataset',
                'verbose_name_plural': 'Datasets',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_name', models.CharField(help_text='Equipment identifier (e.g., P-101, R-201)', max_length=100)),
                ('equipment_type', models.CharField(help_text='Type of equipment (e.g., Pump, Reactor, Heat Exchanger)', max_length=50)),
                ('flowrate', models.FloatField(help_text='Flowrate in m³/h', validators=[django.core.validators.MinValueValidator(0.0, message='Flowrate cannot be negative'), django.core.validators.MaxValueValidator(10000.0, message='Flowrate value is unrealistic')])),
                ('pressure', models.FloatField(help_text='Pressure in bar', validators=[django.core.validators.MinValueValidator(0.0, message='Pressure cannot be negative'), django.core.validators.MaxValueValidator(1000.0, message='Pressure value is unrealistic')])),
                ('temperature', models.FloatField(help_text='Temperature in °C', validators=[django.core.validators.MinValueValidator(-273.15, message='Temperature below absolute zero'), django.core.validators.MaxValueValidator(5000.0, message='Temperature value is unrealistic')])),
                ('dataset', models.ForeignKey(help_text='Parent dataset this equipment belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='equipment_records', to='equipment.dataset')),
            ],
            options={
                'verbose_name': 'Equipment',
                'verbose_name_plural': 'Equipment',
                'ordering': ['equipment_name'],
                'indexes': [models.Index(fields=['dataset', 'equipment_type'], name='equipment_e_dataset_c21356_idx'), models.Index(fields=['equipment_name'], name='equipment_e_equipme_a01e15_idx')],
            },
        ),
    ]
